backend = "glx";  # Lower power usage than GLX
vsync = false;        # Slightly more tearing, but saves GPU cycles

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
corner-radius = 0;

opacity-rule = [
  "100:class_g = 'Dunst'",
  "95:class_g = 'obsidian'",
  "90:class_g = 'firefox'",
  "90:class_g = 'Chromium'",
  "90:class_g = 'kitty'",
  "95:class_g = 'vesktop'",
  "95:class_g = 'code-oss'",
  "90:class_g = 'Spotify'",
  "90:class_g = 'Anki'",
];

shadow = false;       # Disable shadows to reduce GPU load
fading = false;       # No fading animations

