# --------
# nibir's picom.conf
# --------

backend = "glx";
vsync = true;
use-damage = true;

# Opacity Rules
inactive-opacity = 1.0;  # Inactive windows 90% opaque
active-opacity = 1.0;  # Active windows fully visible
frame-opacity = 0.9;  # Border/frame opacity
corner-radius = 0;  # Smooth rounded corners

# Exclude fullscreen apps from opacity
opacity-rule = [
    "100:(fullscreen = true) && (class_g = 'zen')",
    "100:class_g = 'Dunst'",
    "92:class_g = 'obsidian'",  
    "86:class_g = 'firefox'",
    "86:class_g = 'qutebrowser'",
    "92:class_g = 'zen'",
    "88:class_g = 'Chromium'",   
    "85:class_g = 'kitty'", 
    "87:class_g = 'emacs'",
    "92:class_g = 'vesktop'", 
    "92:class_g = 'code-oss'", 
    "90:class_g = 'Spotify'", 
    "94:class_g = 'Anki'",
    "94:class_g = 'gnome-calendar'"
];


# shadows
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.7;
shadow-offset-x = -7;
shadow-offset-y = -7;

# fading
fading = true;
fade-in-step = 0.07;
fade-out-step = 0.07;
fade-delta = 7;

# blur (applies only to the windows with opacity rule)
blur: {
   method = "dual_kawase";
   strength = 1.5;
};
