backend = "xrender";  # Use OpenGL for better performance
vsync = true;  # Reduce screen tearing
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = false;

# Opacity Rules
inactive-opacity = 1.0;  # Inactive windows 90% opaque
active-opacity = 1.0;  # Active windows fully visible
frame-opacity = 0.9;  # Border/frame opacity
corner-radius = 0;  # Smooth rounded corners

# Exclude fullscreen apps from opacity
opacity-rule = [
#    "100:fullscreen = true",
    "100:class_g = 'Dunst'",
    "92:class_g = 'obsidian'",  # Makes Obsidian 90% opaque
    "86:class_g = 'firefox'",   # Firefox at 80%
    "88:class_g = 'Chromium'",   # Firefox at 80%
    "85:class_g = 'kitty'", # Terminal at 85%
    "92:class_g = 'vesktop'", # Terminal at 85%
    "90:class_g = 'Spotify'", # Terminal at 85%
    "90:class_g = 'Anki'", # Terminal at 85%
];

# Shadows (Optional)
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.7;
shadow-offset-x = -7;
shadow-offset-y = -7;

# Fade Animations (Optional)
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# Blur (Only for transparent terminals)
blur: {
    method = "kawase";
    strength = 17;
    background = false;
    kernel = "3x3box";
};

