backend = "glx";  # Use OpenGL for better performance
vsync = true;  # Reduce screen tearing
glx-no-stencil = true;

# Opacity Rules
inactive-opacity = 1.0;  # Inactive windows 90% opaque
active-opacity = 1.0;  # Active windows fully visible
frame-opacity = 0.9;  # Border/frame opacity
corner-radius = 0;  # Smooth rounded corners

# Exclude fullscreen apps from opacity
opacity-rule = [
    # "100:(fullscreen = true) && (class_g = 'zen')",
    "100:class_g = 'Dunst'",
    "92:class_g = 'obsidian'",  
    "86:class_g = 'firefox'",   
    "92:class_g = 'zen'",
    "88:class_g = 'Chromium'",   
    "85:class_g = 'kitty'", 
    # "87:class_g = 'Emacs'", 
    # "87:class_g = 'emacs'", 
    "92:class_g = 'vesktop'", 
    "92:class_g = 'code-oss'", 
    "90:class_g = 'Spotify'", 
    "90:class_g = 'Anki'", 
];


# Shadows (Optional)
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.7;
shadow-offset-x = -7;
shadow-offset-y = -7;

# Fade Animations (Optional)
fading = true;
fade-in-step = 0.07;
fade-out-step = 0.07;
fade-delta = 7;

# Blur (Only for transparent terminals)
#blur: {
#    method = "kawase";
#    strength = 17;
#    background = false;
#    kernel = "3x3box";
#};
