#! /bin/sh

# -------
# nibir's bspwmrc
# -------

# stuff to run the system
## polybar
pkill polybar
~/.config/bspwm/polybar.sh &

## keymaps & sxhkd
setxkbmap -model pc105 -layout us -variant cmk_ed_us -option grp:alt_shift_toggle,misc:extend,lv5:caps_switch_lock,grp:shifts_toggle,compose:menu -v 9

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

## feh (wall)
feh --bg-scale ~/.dotfiles/assets/walls/oil\ painting.png &
xsetroot -cursor_name left_ptr

## dunst (notif)
dunst &

## picom (compositor)
picom &

## redshift (for bluelight filter)
redshift &

## polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


#
# bspwm specific configs
#

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config top_padding 25
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a TelegramDesktop state=floating
bspc rule -a vesktop state=floating
bspc rule -a mpv state=floating follow=on
bspc rule -a Screenkey manage=off

#
# autostart programs
#

## easy effects
easyeffects --gapplication-service &

## safeeyes
safeeyes --gapplication-service &

## udiskie
udiskie &


## nicotine
#nicotine -n &


# end of story (for now)
