#! /bin/sh

#
# Nibir's bspwmrc (2025)
#

# stuff to run the system
## polybar
pkill polybar
~/.config/bspwm/polybar.sh &

## sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

## feh (wall)
feh --bg-scale /mnt/Files/Media/Pictures/Background/mono.jpg &

## dunst (notif)
dunst &

## picom (compositor)
picom &

## command to get the second monitor
xrandr --output HDMI-0 --primary --mode 1920x1080 --refresh 74.97 --pos 0x0 --output eDP-1-1 --mode 1920x1080 --pos 1920x0

## redshift (for bluelight filter)
redshift -l 26.44:92.03 &

# scripts
~/.config/bspwm/cleanfullscreen &
bash ~/.config/bspwm/setkb.sh &
python3 ~/.dotfiles/scripts/remindme.py &

#
# bspwm specific configs
#

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor eDP-1-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop state=floating
# bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# autostart programs
#

## obsidian
bspc rule -a obsidian desktop=^1 focus=off -o
obsidian &

## firefox
bspc rule -a firefox desktop=^2 focus=off -o
firefox &

## qbittorrent
qbittorrent &

## telegram-desktop
bspc rule -a telegram-desktop desktop=^0 focus=off -o
telegram-desktop &

## easy effects
easyeffects --gapplication-service &

## blueman (for bluetooth)
blueman-applet &

## nicotine
nicotine -n &


# end of story (for now)
