#!/usr/bin/env bash

case "$(printf "kill\nwifi\nexam\ntablet" | dmenu -i -c -l 4)" in
	kill) ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	#zzz) slock systemctl suspend -i ;;
	#reboot) systemctl reboot -i ;;
	#shutdown) shutdown now ;;
    wifi) wifi toggle >/dev/null 2>&1 && notify-send "$(wifi)";;
    exam) ~/.dotfiles/scripts/exam ;;
    tablet) systemctl --user restart opentabletdriver.service && notify-send "Reloaded Tablet Configurations" ;;
	*) exit 1 ;;
esac
