#     _                   __
#    (_)___  ____  __  __/ /______
#   / / __ \/ __ \/ / / / __/ ___/
#  / / / / / /_/ / /_/ / /_(__  )
# /_/_/ /_/ .___/\__,_/\__/____/
#        /_/

input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
}

input 2:10:TPPS/2_Elan_TrackPoint {
    accel_profile flat
    pointer_accel 0.3
}

input 7119:2208:HID_1bcf:08a0_Mouse {
    left_handed enabled
}

input * {
    xkb_model pc105
    xkb_layout us
    xkb_variant cmk_ed_us
    xkb_options grp:alt_shift_toggle,misc:extend,lv5:caps_switch_lock,grp:shifts_toggle,compose:menu
}
