#                           _ __
#   ____  ____  ____ ______(_) /___  __
#  / __ \/ __ \/ __ `/ ___/ / __/ / / /
# / /_/ / /_/ / /_/ / /__/ / /_/ /_/ /
# \____/ .___/\__,_/\___/_/\__/\__, /
#     /_/                     /____/

for_window [app_id="firefox"] opacity 0.82
for_window [app_id="qutebrowser"] opacity 0.86
for_window [app_id="obsidian"] opacity 0.92
for_window [app_id="Alacritty"] opacity 0.85
#for_window [app_id="emacs"] opacity 0.87
for_window [app_id="vesktop"] opacity 0.85
for_window [app_id="Anki"] opacity 0.94

for_window [app_id="mpv"] floating enable
