#                __              __
#   ____  __  __/ /_____  __  __/ /_
#  / __ \/ / / / __/ __ \/ / / / __/
# / /_/ / /_/ / /_/ /_/ / /_/ / /_
# \____/\__,_/\__/ .___/\__,_/\__/
#               /_/


output * bg "/home/nibir/.dotfiles/assets/walls/oil painting.png" fill
# output * bg "#1e1e2e" solid_color

font pango:Pragmasevka Nerd Font 13

client.focused          #88c0d0 #88c0d0 #2e3440 #88c0d0 #88c0d0
client.focused_inactive #3b4252 #3b4252 #d8dee9 #3b4252 #3b4252
client.unfocused        #2e3440 #2e3440 #d8dee9 #2e3440 #2e3440
client.urgent           #bf616a #bf616a #eceff4 #bf616a #bf616a

default_border pixel 1
