#!/bin/bash

# searching for vmic
if ! pactl list modules | grep -q "vmic" ; then
    echo "🛠 Creating vmic..."
    pactl load-module module-null-sink media.class=Audio/Source/Virtual sink_name=vmic channel_map=front-left,front-right
    sleep 1
else
    echo "✅ vmic already exists."
fi

# launching reaper
echo "🚀 Launching REAPER with PIPEWIRE_LATENCY=64/48000..."
PIPEWIRE_LATENCY=128/48000 reaper &

sleep 5

echo "🔗 Connecting REAPER → vmic..."
pw-link "REAPER:out1" "vmic:input_FL"
pw-link "REAPER:out2" "vmic:input_FR"
