#!/bin/sh

# source: https://raw.githubusercontent.com/IanLeCorbeau/dotfiles/refs/heads/master/.local/bin/winhide

hidden=$(bspc query -N -n .hidden -d focused)

if [ -z "$hidden" ]; then
	bspc node focused -g hidden=on
else
	bspc node "$hidden" -g hidden=off
fi
